Team Component and Layout
anchour/murphys-magic-client-html pull request #26
Opened 2023-05-26 19:22 UTC by rpmcguire18

2023-05-26 19:30 UTC, mrobit requested changes
Minor changes here; overall looks good.

2023-05-26 19:30 UTC, mrobit commented on src/scripts/components/TeamMembers.tsx
> +  showCopyComponent?: boolean;
The cool thing about typescript interfaces is that they can extend other interfaces – it might not be in your codebase yet, but I wrote a `DisableCopyComponent` interface that you can extend, e.g.

```
interface TeamMemberProps extends DisableCopyComponent {
// your stuff here
}
```

and it will inherit the `disableCopy` interface stuff. It'll make our life approx 0.25% easier for writing this stuff up in the future.

2023-05-26 19:30 UTC, mrobit commented on src/scripts/pages/Collections.tsx
> +        <div className="page-section--tall text-column__one--centered color-background-bone">
There's a `bg-background-bone` class for this instead of `color-background-bone`. The `color-` one shouldn't be necessary – that was an oversight on my part.

2023-05-26 19:30 UTC, mrobit commented on src/scripts/pages/CollectionsStandard.tsx
> +        <div className="page-section--tall text-column__one--centered color-background-bone">
Same bit about `color-background-bone`

2023-05-26 19:31 UTC, mrobit commented on src/scripts/components/TeamMembers.tsx
> +  showCopyComponent?: boolean;
If you have the `DisableCopyComponent` interface available in your codebase you can do this – otherwise don't worry about it rn. It might not be merged in to `main` yet, i haven't checked.

2023-05-27 18:11 UTC, rpmcguire18 commented on src/scripts/components/TeamMembers.tsx
> +  showCopyComponent?: boolean;
I can't get this to work, it keeps kicking back errors saying the disableCopy is not valid. Leaving it as is for now

2023-05-30 13:49 UTC, merged